{% set name = "geoserver-rest" %}
{% set version = "2.9.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a1b16b6c81f8b27308b332afc9dcb9c4adbb0329f15fa687d595151f0075de1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - pip
    - requests
    - pygments
    - xmltodict

test:
  imports:
    - geo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gicait/geoserver-rest
  license: MIT
  license_file: LICENSE
  summary: The package for management of geospatial data in GeoServer.
  description: |
    The geoserver-rest package is useful for the management for geospatial data in GeoServer. The package is useful for the creating, updating and deleting geoserver workspaces, stores, layers, and style files.
  dev_url: https://github.com/gicait/geoserver-rest

extra:
  recipe-maintainers:
    - iamtekson

  optional-dependencies:
    all:
      - gdal
      - seaborn
      - matplotlib
    style:
      - gdal
      - seaborn
      - matplotlib
