{% set name = "geoserver-rest" %}
{% set version = "1.5.7" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32269c52dbfdc7c876605df39d1861ec42d297778f1f2b585bf069dd9d56a50a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - pip
    - gdal
    - seaborn
    - pycurl
    - psycopg2

test:
  imports:
    - geo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gicait/geoserver-rest
  license: MIT
  license_file: LICENSE
  summary: The package for management of geospatial data in GeoServer.
  description: |
    The geoserver-rest package is useful for the management for geospatial data in GeoServer. The package is useful for the creating, updating and deleting geoserver workspaces, stores, layers, and style files.
  dev_url: https://github.com/gicait/geoserver-rest

extra:
  recipe-maintainers:
    - iamtekson
